acr-sync/check-acr-aks-sync-rest.sh

[AB#408]
```
[ ] Yes
[x] No
```

Increase max results. Add extra logging

---

acr-sync/check-acr-aks-sync-rest.sh

[AB#408]
```
[ ] Yes
[x] No
```

Add debug logging. Add max results var.

---

acr-sync/check-acr-aks-sync-rest.sh

[AB#408]
```
[ ] Yes
[x] No
```

Exclude pods with "Completed" status

---

acr-sync/check-acr-aks-sync-rest.sh

[AB#408]
```
[ ] Yes
[x] No
```

Use tags acr api and check lastUpdated tag

---

acr-sync/check-acr-aks-sync-rest.sh

Fix status exclusion check

---

acr-sync/check-acr-aks-sync-rest.sh

[AB#408]
```
[ ] Yes
[x] No
```

Retry acr operations

---

acr-sync/check-acr-aks-sync-rest.sh

Do not stop in case of single repo error

---

acr-sync/check-acr-aks-sync-rest.sh

Use cluster name variable from env injector

---

acr-sync/check-acr-aks-sync-rest.sh

Whitelist Docmosis

---

acr-sync/check-acr-aks-sync-rest.sh

- Determining acr from $image reference
- Removing Camunda and Docmosis from $skip_namespaces
```
[ ] Yes
[X] No
```

Determining acr from $image reference

---

acr-sync/check-acr-aks-sync-rest.sh

New acr_token per namespace to allow for hmctsprivate token
```
[ ] Yes
[X] No
```

New acr_token per namespace to allow for hmctsprivate token

---

acr-sync/check-acr-aks-sync-rest.sh

Trying authentication for hmctsprivate

---

acr-sync/check-acr-aks-sync-rest.sh

Avoid escaping issues

---

.github/workflows/helm-base-versions.yaml

Add docker image release pipeline

---

helm-base-versions/example-job.yaml
helm-base-versions/helm-chart-base-versions.sh

Add slack notify to team channel when running deprecated version

---

helm-base-versions/helm-chart-base-versions.sh

Remove duplicate charts for notifications and make slack notifications optional

---

helm-base-versions/helm-chart-base-versions.sh

skip cosmos when sending message to slack

---

helm-base-versions/helm-chart-base-versions.sh

Remove duplication in cosmos when same chart is used multiple times for different HR like demo

---

helm-base-versions/helm-chart-base-versions.sh
helm-base-versions/send-notification-to-slack.py

Split notify to different script to run from only one cluster per day

---

helm-base-versions/helm-chart-base-versions.sh
helm-base-versions/send-notification-to-slack.py

fix notification when the chart isn't loaded properly

---

acr-sync/check-acr-aks-sync-rest.sh

To reduce noise and still have visibility
```
[ ] Yes
[x] No
```

send notifications to default channel only when team channel not found

---

.github/workflows/failed-deployments.yaml
failed-deployments/Dockerfile
failed-deployments/example-job.yaml
failed-deployments/failed-deployments.sh
failed-deployments/send-json-to-cosmos.py
failed-deployments/send-notification-to-slack.py

Add failed deployment scripts and workflow

Add failed deployment scripts and workflow

---

failed-deployments/failed-deployments.sh

skip namespaces to test

---

failed-deployments/failed-deployments.sh

Fix file name

---

failed-deployments/failed-deployments.sh

Adds back in reform scan as there is a failed deployment there

Adds back in reform scan as there is a faile deployment there

---

failed-deployments/failed-deployments.sh
failed-deployments/send-notification-to-slack.py

Dtspo 14217 add namespace

---

failed-deployments/failed-deployments.sh
failed-deployments/send-notification-to-slack.py

Update slack notifications

---

failed-deployments/send-notification-to-slack.py

Update failed_deployments map and add some debug steps

Update failed_deployments map and add some debug steps

---

failed-deployments/failed-deployments.sh
failed-deployments/send-notification-to-slack.py

Adds if statemate to send notification if enabled

Dtspo 14217 add notify flag

---

helm-base-versions/helm-chart-base-versions.sh

[DTSPO-17348](https://tools.hmcts.net/jira/browse/DTSPO-17348)
Have tested the output of this remains the same even with the new location locally

DTSPO-17348: Point to new location

---

failed-deployments/failed-deployments.sh
failed-deployments/send-notification-to-slack.py

Update message and add namespaces into scope

Update message and add namespaces into scope

---

helm-base-versions/send-json-to-cosmos.py

move cosmosdb to use managed-identity

move cosmosdb environment variable to use managed-identity

---

helm-base-versions/Dockerfile
helm-base-versions/send-notification-to-slack.py

add azure identtiy to docker file and remove cosmosdb authentication from slack as it is using helm-base-versions resource too  https://github.com/hmcts/cnp-flux-config/blob/master/apps/monitoring/helm-base-versions-slack/kustomization.yaml

add-identtiy-into-dockerfile-remove-cosmosdb-authenication-from-slack

---

helm-base-versions/helm-chart-base-versions.sh
helm-base-versions/send-json-to-cosmos.py

fix issue with named arugment. getting issue on pod 
fees-pay-ccpay-cpo-callback-function chart not loaded, marking as error
usage: send-json-to-cosmos.py [-h] --chart_name CHART_NAME --namespace
NAMESPACE --cluster_name CLUSTER_NAME
--deprecated_chart_name DEPRECATED_CHART_NAME
--current_version CURRENT_VERSION
--is_deprecated IS_DEPRECATED --flag FLAG
[--is_error]
send-json-to-cosmos.py: error: the following arguments are required: --chart_name, --namespace, --cluster_name, --deprecated_chart_name, --current_version, --is_deprecated, --flag

fix issue with named-arguments on script

---

helm-base-versions/helm-chart-base-versions.sh

remove true form isError

---

acr-sync/check-acr-aks-sync-rest.sh

See [DTSPO-18508](https://tools.hmcts.net/jira/browse/DTSPO-18508)
remove silence from curl for debug message

remove silence from curl for debug message
